name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        build_type: [Release, Debug]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
        make -j$(nproc)
    
    - name: Test executable
      run: |
        # Test that binary exists and runs
        test -f build/filesystem-indexer
        ./build/filesystem-indexer --help > /dev/null
        echo "✓ Executable test passed"
    
    - name: Upload build artifacts
      if: matrix.build_type == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: filesystem-indexer-${{ matrix.os }}
        path: build/filesystem-indexer
        retention-days: 30